### ISSUE TITLE
Not Working with PHP version 8

### ISSUE THREAD

**Issue by Mainul12501** [s1k3/laravel_bangla_date#2]
This package not working on php v8. It returns with this error
``` [InvalidArgumentException]                                                                                              
  Package s1k3/bangla-date has a PHP requirement incompatible with your PHP version```
  Is it compatible with PHP v8?

**Comment by s1k3** [comment]
I have tested on php 7.3 & php 7.4. as the basic laravel reuirements but have not tested for php 8 which needs to be inspected if you find any kind of error for php 8 plaease share that error that will be a help
